### ISSUE TITLE
Problem In Signing of Pdf with externalSiging service (eSign)

### ISSUE THREAD

**Issue by arjunbpune** [LibrePDF/OpenPDF#31] opened 2017-06-22 14:10 UTC
Hi ,

we want to sign the pdf with external signature provided by esign service.we have used openpdf 1.0.1..
the problem is we are unable to calculate the exclusion size of signature appearance before preclose..
please find below code - 

		byte[] signeddata = null;
		PdfSignatureAppearance pdfSigApp=null;
		File destFile=null;
		PdfReader reader=null;
		 ByteArrayOutputStream arrayOutputStream = new ByteArrayOutputStream();
		
		reader = new PdfReader(signingHelper.getSrc());
		destFile = new File(signingHelper.getDest());
	   
		OutputStream os = arrayOutputStream;
		
		PdfStamper pdfStamper = PdfStamper.createSignature(reader,os, '\0',null, true);
		pdfSigApp = pdfStamper.getSignatureAppearance();

		

		pdfSigApp.setVisibleSignature("SignatureField1[0]");// for existing
													// signaure feild
		SimpleDateFormat dt = new SimpleDateFormat("dd-MMM-yyyy");
		String formatedDate = dt.format(new Date());													// pass name of
															// field
		
		pdfSigApp.setLayer2Text("Digitally Signed" + "\nReason: " + signingHelper.getReason()
		+"\nDate: "+formatedDate+"\nLocation: " + signingHelper.getLocation());
		Font font = new Font();
		//font.setColor(Color);

		font.setSize(9);
		pdfSigApp.setLayer2Font(font);
		

		pdfSigApp.setLocation(signingHelper.getLocation());
		// pdfSigApp.set
		PdfSignature sigDic = new PdfSignature(PdfName.ADOBE_PPKMS, PdfName.ADBE_PKCS7_DETACHED);
		
		sigDic.put(PdfName.FT, PdfName.SIG);
		sigDic.setReason(signingHelper.getReason());
		sigDic.setLocation(signingHelper.getLocation());

		
		pdfSigApp.setCryptoDictionary(sigDic);
		------------------------------
		HashMap exclusions = new HashMap();
		
		
		exclusions.put(PdfName.CONTENTS,new Integer(7622));  //== Here is problem how to  caclucate this Value ?
		

		pdfSigApp.preClose(exclusions);
		LOGGER.info("exclusions:"+exclusions);
		
		String hashPdf = generateSha256HashInHexForPdf(pdfSigApp.getRangeStream());

		//sending this hash to external service for sining----geting pkcs7 signature in response..
				
			signeddata = Base64.getDecoder().decode(pkcs7Signature);
			
			byte out[] = new byte[signeddata.length];
			System.arraycopy(signeddata, 0, out, 0, signeddata.length);
			updates.put(PdfName.CONTENTS, new PdfString(out).setHexWriting(true));
			pdfSigApp.close(updates);
			
			reader.close();
			FileOutputStream fileOutputStream = new FileOutputStream(destFile);
			fileOutputStream.write(arrayOutputStream.toByteArray());
			fileOutputStream.close(); 

please provide suggestions or help in above code... 

Thanks,
Arjun

**Comment by andreasrosdal** [comment] 2017-06-22 16:07
Hello Arjun,

Thanks for reporting this issue.

> the problem is we are unable to calculate the exclusion size of signature appearance before preclose..

Do you get any error messages? What do you yourself think is the cause of this problem? Would you be interested in me fixing this problem as a paid job for you?  If you can provide some more information, then perhaps I could help you better.

Best regards,
Andreas R.

**Comment by arjunbpune** [comment] 2017-06-22 16:21
the problem is i am not able to estimate the exact value for exclusion value for preclose...
like if i given some random number like - exclusions.put(PdfName.CONTENTS,new Integer(7000));
after that signing will be failed with error - The key /Contents is too big. Is 7622, reserved 7000...
also i we give some greater number ..then everything works fine but after opening signed pdf with adobe reader...it shows signature is invalid  with below error details - 
Error during signature verification.  

Signature contains incorrect, unrecognized, corrupted or suspicious data.
Support Information: SigDict /Contents illegal data

so if we put 7622 value it will works fine with that person signature..if another signature(diff person) is applied...value changes...

**Comment by arjunbpune** [comment] 2017-06-22 17:21
So How i can i calculate/estimate the value for exclusion with dynamically for each external (pkcs7) signature ?

**Comment by andreasrosdal** [comment] 2017-06-22 17:27
OpenPDF is an open source project, so you have access to the source code, which should help you understand this issue better. Unfortunately, I don't know the answer to your question directly.  This would take some some hours to find out. Perhaps someone reading this issue will be able to help you.

**Comment by andreasrosdal** [comment] 2018-09-11 07:14
Do you still get this problem in OpenPDF 1.2.3?

**Comment by testn** [comment] 2023-01-10 07:55
any updates on this? Is it fully supported?

**Comment by andreasrosdal** [comment] 2024-02-08 11:06
Closing since 2017. Please reopen if needed.

**Closed by andreasrosdal** 2024-02-08 11:06 UTC
Labels: bug, help wanted
