### ISSUE TITLE
NullPointerException when opening PDF

### ISSUE THREAD

**Issue by kaufmann1** [LibrePDF/OpenPDF#720] opened 2022-04-27 09:37 UTC
**Describe the bug**
OpenPDF throws a NullPointerException when creating a new reader instance.
` try (PdfReader reader = new PdfReader(new FileInputStream(inputFile))) {`
The PDF is a singled paged document with a size of ~450 KB.

**To Reproduce**
For confidentiality reasons, I cannot share the pdf file.
In my case PdfReader.getPdfObject returns null. Most functions that call getPDFObject have a null check.
Maybe it would be a solution to add the null check to PdfReader.iteratePages too

**Expected behavior**
I expect the PDF to open, isntead of throwing errors.

**Screenshots**
![BugReportPDFLib](https://user-images.githubusercontent.com/7513322/165484171-570d943b-7dd9-4a70-88ea-05e52cb30357.png)

**System (please complete the following information):**
 - OS: Bug occurs with Windows and Unix using OpenJDK 11.0.2

**Comment by kaufmann1** [comment] 2022-04-27 09:47
The pdf file can be openend with all common PDF programs like Adobe, PDF24, Edge or Chrome

**Comment by kaufmann1** [comment] 2022-04-28 10:05
I think OpenPDF should have some error tolerance to a certian degree. There are so many different libs/app that produce PDFs, that faulty non conform PDFs are practically predestined.
My opionion is that OpenPDF should handle those files. If common readers can display the files, that OpenPDF should also be able to. If OpenPDF can't process "real world PDF" files, why should I use it ?

**Comment by mkl-public** [comment] 2022-04-28 17:32
Well, not really.

Please don't forget the big difference between the use cases.

After loading a faulty PDF and attempting to repair the errors, a PDF processor _displaying the PDF_ has a user on the other side of the screen who can decide whether the document looks ok or not. So if the "repair" resulted in something obviously broken, the user will reject the file for further processing.

PDF libraries like OpenPDF, though, often are used in _fully automatic_ use cases. Their outputs often are immediately forwarded to thousands of customers or stored in legally required archives. If in such a case a "repair" results in rubbish, you may fail to gain thousands of customers or - probably even worse - in some next audit get into serious trouble for not being able to provide documents the law requires from you.

And there is another problem, as soon as you have to deal with serious documents - invoices, contracts, medical prescriptions, ... - then any defect in the document should in a PDF viewer result in a matching error message, probably with an option to try and repair, but not in a silent repair without message; after all, the error in combination with the repair attempt may have falsified the displayed data with serious repercussions.

**Comment by kaufmann1** [comment] 2022-04-30 13:21
The use case where I use OpenPDF is exactly the opposite.
My application consumes user created PDFs. 
We try to extract a specific number from the documents sent to us. If this is possible, the document can be processed further automatically.
If the PDF cannot be opened, the document must be processed by an employee.

**Comment by andreasrosdal** [comment] 2022-05-09 10:17
Thanks for reporting this error. I agree, this bug is a critical bug in OpenPDF, and should be fixed so that no NullPointerException is thrown. Please merge the pull request #721.

This is the stacktrace I get for this NullPointerException:

Caused by: java.lang.NullPointerException
	at com.lowagie.text.pdf.PdfReader$PageRefs.iteratePages(PdfReader.java:3729)
	at com.lowagie.text.pdf.PdfReader$PageRefs.readPages(PdfReader.java:3561)
	at com.lowagie.text.pdf.PdfReader$PageRefs.<init>(PdfReader.java:3532)
	at com.lowagie.text.pdf.PdfReader$PageRefs.<init>(PdfReader.java:3501)
	at com.lowagie.text.pdf.PdfReader.readPages(PdfReader.java:1105)
	at com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:627)
	at com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:212)
	at com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:196)

**Closed** 2022-05-11 21:27 UTC
Labels: bug

**Comment by kaufmann1** [comment] 2022-05-12 12:04
THX
