### ISSUE TITLE
NullPointerException due to missing trailer (on bad startxref?)

### ISSUE THREAD

**Issue by mintern** [LibrePDF/OpenPDF#69] opened 2018-02-16 20:26 UTC
In 1.0.5, we got a NullPointerException with the following stacktrace while trying to read a PDF:

```
PdfReader.java:1112 - com.lowagie.text.pdf.PdfReader.readPages
PdfReader.java:622 - com.lowagie.text.pdf.PdfReader.readPdf
PdfReader.java:282 - com.lowagie.text.pdf.PdfReader.
PdfReader.java:295 - com.lowagie.text.pdf.PdfReader.
```

Based on the line numbers, `trailer` must be null. Tracing through the execution, this can happen in the following sequence of events:

1. `readPdf` calls `readXref`, which is supposed to set `trailer` (among other things).
2. `readXref` doesn't find a valid `startxref` and throws an exception, or `readXrefSection` throws an exception due to an invalid `xref`.
3. `readPdf` catches the exception and calls `rebuildXref`
4. That method tries to set the `trailer`, too, but it can return without actually setting it.
5. `readPdf` proceeds to `readPages`, `trailer` is unset, and we get an NPE.

I'm not sure what the proper fix would be, though. Should one of the caught exceptions instead bubble out of `readPdf`? Should `rebuildXref` set `trailer` to an empty `PdfDictionary` if it doesn't find the actual trailer?

Sorry, I'm pretty ignorant about the PDF format in general. This report is just based on working through this exception's execution path.

**Comment by rik86** [comment] 2018-02-16 20:35
Do you have any more information on how to reproduce this error please? Maybe attaching the file you are attempting to read and or a snippet of code you use to read the file, if not even better a unit test? Many thanks

**Comment by mintern** [comment] 2018-02-16 20:43
The code to read the file is `new PdfReader(inputStream)`. This is happening in the constructor.

I'm locating the file now to see if it can be shared.

**Comment by mintern** [comment] 2018-02-16 20:57
Unfortunately, I cannot publish the file, and I don't have enough expertise or time to share a sanitized version. Sorry about that.

**Comment by rik86** [comment] 2018-02-16 21:11
no worries, I'll take a look at this as soon as I can anyway

**Comment by rik86** [comment] 2018-02-17 21:24
Ok, so I have done a fair bit of reading, and this seems to be a problem that has some correlation with Acrobat Reader 9, (not 100% sure though). A file TRAILER in PDFs, is in my understanding a mandatory, although some file do not have a TRAILER keyword followed by a TRAILER dictionary instead they live in the XREF stream dictionary.

Unfortunately I was unable to recreate a unit test because I don't have a PDF with such structure described above. Regarding your comment to provide an empty `PdfDictionary` instead of `null`, it makes sense, but this cannot be a justifiable fix without proper testing.

Given you are unable to share the malformed pdf document, I'd suggest you edit the `PdfReader` class, specifically make `protected PdfDictionary readXrefSection()` method return an empty `PdfDictionary` instead of `null` just as you suggested. Then see if you can read your PDF, if you can then I guess there should be a possible fix, otherwise it is probably a corrupted file.

Hope this information helps you.

**Comment by andreasrosdal** [comment] 2018-02-18 05:24
I suggest someone adds checks for NullPointerExceptions in this methos:  https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfReader.java#L1111

**Comment by daviddurand** [comment] 2018-04-21 22:49
I've looked at this before (thought, in fact, I'd fixed it, once upon a time, but there may be more than one trailer check/reference).

Trailers are no longer required for PDF 1.5 and greater. I'll try to make an example, and take a look at the crash.

The trailer isn't really used for much, since it's just an optimization for finding the directory by looking at the end of a file.

**Comment by applikationsprogramvara** [comment] 2021-03-19 01:37
I have `NullPointerException` in [PdfReader.java](https://github.com/LibrePDF/OpenPDF/blob/116b38cdbe30385161444976a2c418446fdaf0a5/openpdf/src/main/java/com/lowagie/text/pdf/PdfReader.java#L1076) in `readPages` because `trailer` is null.

``` java
  protected void readPages() throws IOException {
    catalog = trailer.getAsDict(PdfName.ROOT);            << NullPointerException
```

This is pretty critical, because it happens at the very beginning and nothing can't be done with the document.

The problem appeared as mentioned before because `startxref` can't be read correctly. I also can't share my PDF. But here is a screenshot of its last bytes. I scrolled to the very end, lines are wrapped.

![image](https://user-images.githubusercontent.com/38891920/111717625-b62f8800-8858-11eb-8681-b3a4141cd8d7.png)

It appeared, that the PDF has ~2050 bytes after `startxref` to the end of the file. 

But in [PRTokeniser.java](https://github.com/LibrePDF/OpenPDF/blob/116b38cdbe30385161444976a2c418446fdaf0a5/openpdf/src/main/java/com/lowagie/text/pdf/PRTokeniser.java#L219) in `getStartxref` somehow fixed 1024 bytes are read from the end of the document and this is not enough:

``` java
    public int getStartxref() throws IOException {
        int size = Math.min(1024, file.length());         << hardcoded 1024
        int pos = file.length() - size;
        file.seek(pos);
        String str = readString(1024);                    << once again
        int idx = str.lastIndexOf("startxref");
        if (idx < 0)
            throw new InvalidPdfException(MessageLocalization.getComposedMessage("pdf.startxref.not.found"));
        return pos + idx;
    }
```

I've made an experiment extending `1024` and it worked out well.

I would suggest to think of replacing `1024` with a greater number or just searching `startxref` dynamically from the end of the file.

I am not a big pro in PDFs, but [here](https://stackoverflow.com/questions/11896858/does-the-eof-in-a-pdf-have-to-appear-within-the-last-1024-bytes-of-the-file) I've found a mentioning, that the requirement, that %%EOF should appear at the end of file was dropped from ISO, whatever that means.

**Comment by mkl-public** [comment] 2021-03-19 17:57
>I am not a big pro in PDFs, but here I've found a mentioning, that the requirement, that %%EOF should appear at the end of file was dropped from ISO, whatever that means.

I'm afraid you misinterpreted that. What's meant there is that the _relaxed implementation note by Adobe_ (which only requires the %%EOF to appear _somewhere within the last 1024 bytes of the file_) has been dropped when PDF became an ISO standard.

The ISO standard requires: _The last line of the file shall contain only the end-of-file marker, %%EOF._ And both OpenPDF and iText accept somewhat invalid PDFs with a certain amount of extra trash thereafter.

**Comment by mkl-public** [comment] 2021-03-19 18:07
That been said, your screenshot looks like the extra trash after the %%EOF is actually some PDF content (the _endstream ... stream_ segment is very PDF'ish).

This has the smell of PDFs generated by buggy software that stores PDFs in files inappropriately opened for writing (with `Open` instead of `Create`) or in memory streams with some previous content without making sure to eventually only use the  newly written part.

**Comment by applikationsprogramvara** [comment] 2021-03-19 21:27
@mkl-public thank you for your feedback! 

Now I understand why 1024 is hardcoded here.

I replaced the function mentioned [above](https://github.com/LibrePDF/OpenPDF/issues/69#issuecomment-802447672) via this code:

``` java
    public int getStartxref() throws IOException {
        int step = 1024;
        int pos = file.length();
        int idx;
        do {
            pos = Math.max(0, pos - step);
            file.seek(pos);
            String str = readString(step);
            idx = str.lastIndexOf("startxref");
        } while (pos > 0 && idx < 0);
        if (idx < 0)
            throw new InvalidPdfException(MessageLocalization.getComposedMessage("pdf.startxref.not.found"));
        return pos + idx;
    }
```

It is working universally for me for the usual files as long as for the files with "trash" at the end. I would propose a PR to include the code to the main repository.

The PDF file mentioned above is most likely was produced from [Bluebeam Revu](https://www.bluebeam.com/solutions/revu/). But actually it does not matter, because OpenPDF library should be able to work with any PDF. Users do not care if the original file was produced not according to the standards.

**Comment by asturio** [comment] 2021-03-20 12:57
Pull requests are welcome! 
@mkl-public : Are you fine with the suggested code?

**Comment by mkl-public** [comment] 2021-03-21 18:55
One problem: If the **startxref** occurs partially in one read packet and partially in another, it won't be found. This can be resolved by having the packets overlap, e.g. by initializing `pos` with 

    int pos = file.length() - 8;

and reading a packet with 

    String str = readString(step + 8);

----

One aside, though, I don't concur with

> But actually it does not matter, because OpenPDF library should be able to work with any PDF. Users do not care if the original file was produced not according to the standards.

While users indeed often don't care whether a PDF _was produced not according to the standards_ and expect any file Acrobat Reader can display to be processable by one's software, OpenPDF (or any other PDF library) should not simply give in and allow any deviation from the standard that some PDF viewer somewhere in the wild supports.

One reason those users should understand is that deviations from the standard are open to different interpretations by different software, so something broken may be displayed one way by a tolerant viewer and processed a different way by a tolerant software further processing the file. Thus, what the user wanted to send into some process (which might in the end involve forwarding the resulting PDF out to thousands or millions of customers) might be something different than what is actually processed (and so eventually is read by those thousands or millions of customers in the example). Other reasons are related to attack vectors for forgery of signed data, etc.

So one probably should create some flag (e.g. in some static variable) and only allow such deviations if that flag is set.

**Comment by applikationsprogramvara** [comment] 2021-03-23 01:05
> One problem: If the **startxref** occurs partially in one read packet and partially in another, it won't be found. This can be resolved by having the packets overlap, e.g. by initializing `pos` with

@mkl-public thank you for pointing to the case with packets overlaping. I have updated the code under PR https://github.com/LibrePDF/OpenPDF/pull/505

**Comment by applikationsprogramvara** [comment] 2021-03-23 01:18
> So one probably should create some flag (e.g. in some static variable) and only allow such deviations if that flag is set.

@mkl-public I understand your point. 

I think as long as deviations are still _comprehensible_ and the document can be opened/rendered/etc., it is OK to show some marking "you document is not build according to the standard". If from the other hand OpenPDF chooses to bump such a message to the users while failing to operate such documents, it will be proud following the standards, but the users and other apps will turn away from OpenPDF. 

So I think the truth is somewhere in the middle: you can notify the user about the potential problem and do whatever you can to provide normal operation for the users.

**Closed** 2021-05-02 20:21 UTC
Labels: bug, help wanted
