### ISSUE TITLE
Manual is missing

### ISSUE THREAD

**Issue by literakl** [LibrePDF/OpenPDF#61] opened 2017-12-28 17:29 UTC
I want to evaluate this fork and I miss a manual / simple demo applications. I tried to search for iText tutorials but most of them does not compile with OpenPDF. So I suggest that demos / wiki would be nice for newcommers.

Btw is there some chat for a discussion with OpenPDF developers?

**Comment by asturio** [comment] 2017-12-29 12:43
OpenPDF should work like itext 2.1.7. So any example using itext 2.1.7 should work with OpenPDF too. Examples using iText5 or later are incompatible. (other package hierarchy).

**Comment by asturio** [comment] 2017-12-29 12:44
Please take a look at here: https://github.com/LibrePDF/OpenPDF/issues/53

**Comment by literakl** [comment] 2018-01-01 13:13
Thanks. I may publish some demo in future. I grabbed several existing articles and make them work. But I do not want to enter licensing issues so I will have to rewrite them first.

Btw I have created a tag at stackoverrflow: https://stackoverflow.com/questions/tagged/openpdf
I do not want to submit issues there in github when I do not understand some API. SO is better platform.

**Comment by asturio** [comment] 2018-01-03 19:35
@literakl If you want to contribute with documentation, you are welcome.

**Comment by rik86** [comment] 2018-01-23 11:53
In itext 2.1.7 you could do:

```
import com.lowagie.text.html.simpleparser.HTMLWorker;
			HTMLWorker worker = new HTMLWorker(document);
		
			worker.parse(new StringReader(html));
```
This dos not seem to be the case, so I agree some minimal documentation would be useful. I'll make an attempt to contribute with a PR if I manage to understand how this works.

**Comment by GitMensch** [comment] 2019-02-06 12:15
See #149 for an archived version of the old tutorial.

**Comment by andreasrosdal** [comment] 2019-02-08 07:34
Closing as duplicate of #152. Please contribute to the wiki manual.

**Closed by andreasrosdal** 2019-02-08 07:34 UTC
Labels: help wanted
