### ISSUE TITLE
Image transparency loaded incorrectly - Image's black color "burns out"

### ISSUE THREAD

**Issue by fono** [LibrePDF/OpenPDF#217] opened 2019-08-05 12:58 UTC
In one of our projects we render images to PDF documents in a similar way to backround images in CSS: the image can be offset, tiled, or repeated horizontally/vertically in a placeholder area.
In some cases the black color burns out in the PDF, displaying white instead of black. I managed to create a very simple project to reproduce the issue:
https://github.com/fono/openpdf-test-image

I included some details in the readme of the project.

Please note that this issue was introduced in OpenPDF version 1.2.0 -- it worked fine in 1.1.0.

**Comment by fono** [comment] 2019-08-05 13:10
![result](https://user-images.githubusercontent.com/3025973/62467027-19a79780-b793-11e9-9ef9-690af79905a3.png)

**Comment by andreasrosdal** [comment] 2019-08-06 07:16
OpenPDF 1.2.x switched to using Java ImageIO to load images. This was to move the maintenance of image codec loading code from the OpenPDF project, and use a common library instead.
https://docs.oracle.com/javase/8/docs/api/javax/imageio/package-summary.html

@fono Can you please update the openpdf-test-image project to use OpenPDF 1.3.1 instead, it's the latest version. The code for loading images is different in OpenPDF 1.3.1, although the problem is still present there also. Maybe you could help us debug and fix this problem? OpenPDF is volunteer-based.

**Comment by fono** [comment] 2019-08-06 07:29
I've updated the sample project to use OpenPDF 1.3.1.

At some time I should have a try and debug the issue, but I'm not very familiar with image processing (and also with PDFs), so someone with more experience might be more efficient.

**Comment by andreasrosdal** [comment] 2019-08-06 07:31
Thanks. The relevant code is here:  https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/ImageLoader.java

**Comment by andreasrosdal** [comment] 2019-08-13 05:36
This has been fixed in the latest version. 

@fono Can you please verify?

**Closed by andreasrosdal** 2019-08-13 05:36 UTC
Labels: bug, help wanted

**Comment by fono** [comment] 2019-08-13 09:28
Thanks, our tests regarding the images pass with this release.
